Jmmabanta/feature/website refactor integration
AlbertaSat/ex2_ground_station_software pull request #124
Opened 2022-08-02 00:31 UTC by jmmabanta

Added support for faking responses when using 'dummy' as an interface (`-I dummy`).

Luckily, I've found a way to modify the system path variable (temporarily) when running the website's communication script so that the imports are able to work without any modification!

I've also modified cli.py to mimic the [old version](https://github.com/AlbertaSat/ex2_ground_station_software/blob/e80e1b1478b2a30415fd62c4655be953a79d80f3/src/cli.py#L65) where--if given a list of dictionaries--would pretty print each one out. Apparently, the HOUSEKEEPING.GET_HK command can return multiple dictionaries as a list depending on the arguments (though I could be wrong and this behavior could've changed).

2022-08-02 15:21 UTC, Taylorr82 requested changes

2022-08-03 19:51 UTC, Taylorr82 commented
I'd like to see the results of @tganley testing https://github.com/AlbertaSat/ex2_ground_station_software/pull/125 before we merge this. Is that alright?

2022-08-03 20:07 UTC, jmmabanta commented
Yeah Id prefer that to as I'd like to get the housekeeping part right for the website

2022-08-03 20:09 UTC, jmmabanta commented on src/cli.py
> +                # Housekeeping data can be a list of dicts
Ill wait for #125 to see the format of HK first

2022-08-29 18:18 UTC, jmmabanta commented
Status on #125?

2022-08-29 18:23 UTC, Taylorr82 commented
> Status on #125?

Still no communication from the other teams

2022-09-12 16:35 UTC, Taylorr82 commented
#125 is merged now

2022-09-20 22:54 UTC, jmmabanta commented
Sounds good!. Can you have a final pass looking over my code just in case before merging? (I believe the only big change was adding dummy housekeeping responses and having 'GET_INSTANT_HK' use the hkTransaction instead of the normal transaction)

2022-09-23 18:32 UTC, Taylorr82 approved these changes

2022-09-26 22:56 UTC, merged