Add descriptions for a bunch of ground station commands
AlbertaSat/ex2_ground_station_software pull request #95
Opened 2022-06-10 19:18 UTC by tganley

2022-06-10 19:24 UTC, Taylorr82 commented on src/groundStation/system.py
> +                    },UFH
This looks like an error

2022-06-10 20:16 UTC, jmmabanta requested changes

2022-06-10 20:16 UTC, jmmabanta commented on src/groundStation/system.py
> +                            'what': 'Fetch housekeeping data for the DFGM payload.'
```suggestion
                            'what': 'Fetch housekeeping data for the DFGM payload.',
```
Missed comma

2022-06-15 19:13 UTC, Taylorr82 commented on src/groundStation/system.py
> +                    },UFH
@tganley did you see this?

2022-06-28 22:52 UTC, tganley commented on src/groundStation/system.py
> +                    },UFH
Yes thanks

2022-06-28 23:14 UTC, jmmabanta approved these changes

2022-07-01 16:27 UTC, merged